language: node_js

node_js:
  - stable

before_install:
  - openssl aes-256-cbc -K $encrypted_ca735c92e330_key -iv $encrypted_ca735c92e330_iv -in .travis/travis.enc -out ~/.ssh/id_rsa -d
  - chmod 0600 ~/.ssh/id_rsa
  - npm install -g greenkeeper-lockfile@1

addons:
  ssh_known_hosts: fetalk.xyz

install:
  - npm install

before_script: greenkeeper-lockfile-update

script:
  - make check

after_script: greenkeeper-lockfile-upload

deploy:
  provider: script
  script: make deploy
  on:
    branch: master
