language: node_js

node_js:
  - stable

before_install:
  - openssl aes-256-cbc -K $encrypted_ca735c92e330_key -iv $encrypted_ca735c92e330_iv -in .travis/travis.enc -out ~/.ssh/id_rsa -d
  - chmod 0600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts: fetalk.xyz

install:
  - npm install

script:
  - make check

